# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_macos64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_macos64)
  tejas_config = debug_macos64

else ifeq ($(config),debug_linux64)
  tejas_config = debug_linux64

else ifeq ($(config),debug_windows64)
  tejas_config = debug_windows64

else ifeq ($(config),release_macos64)
  tejas_config = release_macos64

else ifeq ($(config),release_linux64)
  tejas_config = release_linux64

else ifeq ($(config),release_windows64)
  tejas_config = release_windows64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := tejas

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

tejas:
ifneq (,$(tejas_config))
	@echo "==== Building tejas ($(tejas_config)) ===="
	@${MAKE} --no-print-directory -C . -f tejas.make config=$(tejas_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f tejas.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_macos64"
	@echo "  debug_linux64"
	@echo "  debug_windows64"
	@echo "  release_macos64"
	@echo "  release_linux64"
	@echo "  release_windows64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   tejas"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"