# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_macos64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_macos64)
  pixie_config = debug_macos64

else ifeq ($(config),debug_linux64)
  pixie_config = debug_linux64

else ifeq ($(config),debug_win64)
  pixie_config = debug_win64

else ifeq ($(config),release_macos64)
  pixie_config = release_macos64

else ifeq ($(config),release_linux64)
  pixie_config = release_linux64

else ifeq ($(config),release_win64)
  pixie_config = release_win64

else ifeq ($(config),test_macos64)
  pixie_config = test_macos64

else ifeq ($(config),test_linux64)
  pixie_config = test_linux64

else ifeq ($(config),test_win64)
  pixie_config = test_win64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := pixie

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

pixie:
ifneq (,$(pixie_config))
	@echo "==== Building pixie ($(pixie_config)) ===="
	@${MAKE} --no-print-directory -C . -f pixie.make config=$(pixie_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f pixie.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_macos64"
	@echo "  debug_linux64"
	@echo "  debug_win64"
	@echo "  release_macos64"
	@echo "  release_linux64"
	@echo "  release_win64"
	@echo "  test_macos64"
	@echo "  test_linux64"
	@echo "  test_win64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   pixie"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"