name: Pixie Unit Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build and run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: make
        run: make config=test_linux64
      - name: test
        run: ./bin/Test/pixie -tse="Perft Full"
